Refactor role to support CRL
freedomofpress/ansible-role-openssl-node pull request #5
Opened 2017-07-21 21:07 UTC by msheiny

Did some tweaking to allow running this role under a persistent CA environment which is necessary to support things like CRL, and serial number tracking.

Previous design was assuming you were storing a CA in ansible vault and
just spinning off CSRs remotely, pulling those back and signing them, then
ignoring the local environment completely (besides private CA key purge).
This was all well and good but does not play nicely with an environment
where you are tracking CA attributes such as serial numbers and MORE
importantly revocation data.

This big commit tries to rework the tasks to allow such a scenario. It
doesn't set that up but if it detects you are trying to run under a
long-running CA folder (by looking for a crl.pem ), a different task will
kick off that will allow you to sign a CSR and also continue track that
data locally.

2017-07-22 21:34 UTC, conorsch commented on tasks/main.yml
> +    - copy_ca_certs.changed
Nit: should be `copy_ca_certs|changed`

2017-07-22 22:01 UTC, conorsch requested changes
Clean implementation and good documentation of changes. Requested edit for `|changed` filter use.

Also consider using the [tempfile Ansible module](https://docs.ansible.com/ansible/tempfile_module.html) for managing the temporary directories. Not blocking merge for that, though.

2017-07-24 13:30 UTC, msheiny commented
> Clean implementation and good documentation of changes. Requested edit for |changed filter use.

✔️ Addressed that in `8f24aae`. Good  👁 !

> Also consider using the tempfile Ansible module for managing the temporary directories. Not blocking merge for that, though.

That's a good call. I made a ticket to address that in  #7. Thanks for not blocking on that yet. I'd like to get CI wired up ( #6 ) before I do that to make sure I don't have any regressions.

2017-07-24 16:23 UTC, conorsch approved these changes

2017-07-24 16:23 UTC, conorsch commented
>  I made a ticket to address that in #7.

I :heart: rainy-day issues!

2017-07-24 16:23 UTC, merged